#!/bin/bash

# nicked from porges: https://news.ycombinator.com/item?id=7518503



git log --numstat --no-merges --pretty=format:%an \
    | awk '
    author == "" { author = $0; next }
    /^$/ { author = ""; next }
    { added[author] += $1; removed[author] += $2 }
    END { for (author in added) {
    print author, "added", added[author], "removed", removed[author], "sum", added[author]-removed[author]
    } }'\
    | sort -r -n -k 8

