#!/bin/bash
# strip comments and empty lines, good for reading config files

if [ -z "$1" ]; then
	echo "Usage: '$0 [-l] FILE', where -l pipes the output to less instead of STDOUT"
	exit 0
fi

if [ "$1" == "-l" ]; then
	WITHLESS=1
	shift
fi

if [ "$WITHLESS" == 1 ]; then
	grep "^[^#|;]" $1 | less
else
	grep "^[^#|;]" $1
fi
